### PR TITLE
Upgrade to actix 0.12

### PR DESCRIPTION
**Pull request by Freyskeyd**
Signed-off-by: Freyskeyd <simon.paitrault@gmail.com>

### CODE REVIEW

**Comment by Diggsey** [comment]
Thanks! Could you bump this crate version too?

**Comment by Freyskeyd** [comment]
@Diggsey sorry which one?

**Comment by Diggsey** [comment]
`actix-interop` - bumping the major version of a public dependency requires bumping this crate's version too (to 0.3.0)

**Comment by Freyskeyd** [comment]
Oh right, sorry ! It's fixed

**Comment by Diggsey** [comment]
👍

**Pull request merged**
